"""Database connection, session management, and utility functions."""

from api.database.base import get_session, run_in_session
from api.database.connectors import (
    db_count_credentials_by_subjects,
    db_create_credential,
    db_create_mcp_server,
    db_delete_credential,
    db_delete_credentials_by_subject,
    db_delete_mcp_server,
    db_get_credential_by_id,
    db_get_credentials_by_org,
    db_get_credentials_by_subject,
    db_get_mcp_server_by_id,
    db_get_mcp_servers_by_org,
    db_replace_credential,
    db_update_mcp_server,
)
from api.database.dashboard import (
    compute_display_status,
    db_get_active_repos,
    db_get_issue_detail,
    db_get_issues_paginated,
    db_get_lgtm_leaderboard,
    db_get_org_stats,
    db_get_top_pr_authors,
    db_get_workspace_executions,
    db_get_workspace_pull_requests,
    db_get_workspace_stats,
    db_list_issue_repositories,
    db_list_pr_repositories,
)
from api.database.execution import (
    db_create_execution,
    db_get_dispatchable_issues,
    db_get_eligible_dispatch_targets,
    db_get_execution_by_id,
    db_get_failed_execution_count,
    db_get_latest_execution_for_issue,
    db_git_org_has_running_fix_execution,
    db_has_active_execution,
    db_link_execution_pull_requests,
    db_update_execution_container,
    db_update_execution_status,
)
from api.database.identity import (
    db_count_user_identities,
    db_get_identity_by_external_id,
    db_get_or_create_provider_identity,
    db_unlink_identity_from_user,
)
from api.database.instance_settings import (
    db_delete_settings_by_category,
    db_get_setting,
    db_get_settings_by_category,
    db_has_any_git_provider,
    db_insert_setting,
    db_upsert_setting,
)
from api.database.issue import (
    db_create_issue,
    db_get_issue_by_id,
    db_get_issue_by_sentry_id,
    db_update_issue,
)
from api.database.organization import (
    db_claim_dispatch_window,
    db_create_org,
    db_delete_org,
    db_delete_org_by_id,
    db_delete_org_membership,
    db_ensure_org_membership,
    db_get_descendant_orgs,
    db_get_org_by_external_id,
    db_get_org_by_id,
    db_get_org_by_installation_id,
    db_get_org_chain_ids,
    db_get_org_members,
    db_get_org_subtree_ids,
    db_get_orgs_by_workspace,
    db_get_source_orgs,
    db_get_subgroup_repo_counts,
    db_list_gitlab_orgs,
    db_resolve_notify_handles,
    db_resolve_org_token,
    db_update_org,
    db_upsert_org_with_ancestors,
)
from api.database.plugins import (
    db_create_marketplace,
    db_create_marketplace_install,
    db_delete_install,
    db_delete_marketplace,
    db_find_marketplace_install,
    db_get_installation_by_id,
    db_get_installations_by_org,
    db_get_marketplace_by_id,
    db_get_marketplace_by_url,
    db_get_marketplaces_by_org,
    db_update_install,
    db_update_marketplace_sync,
)
from api.database.pull_request import (
    db_get_open_fix_prs_for_git_org,
    db_get_pull_request,
    db_get_pull_request_by_id,
    db_git_org_has_open_fix_pr,
    db_has_active_pr_execution,
    db_link_issue_pull_requests,
    db_upsert_pull_request,
    resolve_workspace_id,
)
from api.database.repository import (
    db_count_enabled_repositories,
    db_count_org_repositories,
    db_create_repository,
    db_delete_repository,
    db_get_enabled_repositories_by_org,
    db_get_mapped_repositories,
    db_get_related_repos,
    db_get_related_repos_bulk,
    db_get_repositories_by_ids,
    db_get_repositories_by_org,
    db_get_repository_by_external_id,
    db_get_repository_by_id,
    db_get_repository_by_org_and_external_id,
    db_get_unmapped_repositories,
    db_link_repos,
    db_list_repositories_by_org,
    db_set_org_repos_enabled,
    db_unlink_repos,
    db_update_repository_mapping,
    db_upsert_repository,
)
from api.database.user import (
    db_create_or_update_user,
    db_get_user_by_email,
    db_get_user_by_id,
)
from api.database.workspace import (
    db_create_workspace,
    db_create_workspace_membership,
    db_ensure_workspace_membership,
    db_get_workspace_by_id,
    db_get_workspace_by_slug,
    db_get_workspaces_by_user,
    db_is_workspace_member,
    db_revoke_workspace_membership_if_no_orgs,
)

__all__ = [
    "get_session",
    "run_in_session",
    # User functions
    "db_create_or_update_user",
    "db_get_user_by_email",
    "db_get_user_by_id",
    # Identity functions
    "db_count_user_identities",
    "db_get_identity_by_external_id",
    "db_get_or_create_provider_identity",
    "db_unlink_identity_from_user",
    # Organization functions
    "db_claim_dispatch_window",
    "db_create_org",
    "db_delete_org",
    "db_delete_org_by_id",
    "db_delete_org_membership",
    "db_ensure_org_membership",
    "db_get_descendant_orgs",
    "db_get_org_by_external_id",
    "db_get_org_by_id",
    "db_get_org_by_installation_id",
    "db_get_org_chain_ids",
    "db_get_org_members",
    "db_get_org_subtree_ids",
    "db_get_orgs_by_workspace",
    "db_get_source_orgs",
    "db_get_subgroup_repo_counts",
    "db_list_gitlab_orgs",
    "db_resolve_notify_handles",
    "db_resolve_org_token",
    "db_update_org",
    "db_upsert_org_with_ancestors",
    # Execution functions
    "db_create_execution",
    "db_get_dispatchable_issues",
    "db_get_eligible_dispatch_targets",
    "db_get_execution_by_id",
    "db_get_failed_execution_count",
    "db_get_latest_execution_for_issue",
    "db_has_active_execution",
    "db_git_org_has_running_fix_execution",
    "db_link_execution_pull_requests",
    "db_update_execution_container",
    "db_update_execution_status",
    "db_update_execution_step",
    # InstanceSetting functions
    "db_delete_settings_by_category",
    "db_get_setting",
    "db_get_settings_by_category",
    "db_has_any_git_provider",
    "db_insert_setting",
    "db_upsert_setting",
    # Issue functions
    "db_create_issue",
    "db_get_issue_by_id",
    "db_get_issue_by_sentry_id",
    "db_update_issue",
    # MCP server + credential functions
    "db_create_mcp_server",
    "db_count_credentials_by_subjects",
    "db_create_credential",
    "db_delete_credential",
    "db_delete_credentials_by_subject",
    "db_delete_mcp_server",
    "db_get_credential_by_id",
    "db_get_credentials_by_subject",
    "db_get_credentials_by_org",
    "db_get_mcp_server_by_id",
    "db_get_mcp_servers_by_org",
    "db_update_mcp_server",
    "db_replace_credential",
    # Plugin marketplace + installation functions
    "db_create_marketplace",
    "db_create_marketplace_install",
    "db_delete_install",
    "db_delete_marketplace",
    "db_find_marketplace_install",
    "db_get_installation_by_id",
    "db_get_installations_by_org",
    "db_get_marketplace_by_id",
    "db_get_marketplace_by_url",
    "db_get_marketplaces_by_org",
    "db_update_install",
    "db_update_marketplace_sync",
    # PullRequest functions
    "db_get_open_fix_prs_for_git_org",
    "db_get_pull_request",
    "db_get_pull_request_by_id",
    "db_git_org_has_open_fix_pr",
    "db_has_active_pr_execution",
    "db_link_issue_pull_requests",
    "db_upsert_pull_request",
    "resolve_workspace_id",
    # Repository functions
    "db_count_enabled_repositories",
    "db_count_org_repositories",
    "db_create_repository",
    "db_delete_repository",
    "db_get_mapped_repositories",
    "db_get_related_repos",
    "db_get_related_repos_bulk",
    "db_get_enabled_repositories_by_org",
    "db_get_repositories_by_ids",
    "db_get_repositories_by_org",
    "db_list_repositories_by_org",
    "db_set_org_repos_enabled",
    "db_get_repository_by_external_id",
    "db_get_repository_by_id",
    "db_get_repository_by_org_and_external_id",
    "db_get_unmapped_repositories",
    "db_link_repos",
    "db_unlink_repos",
    "db_update_repository_mapping",
    "db_upsert_repository",
    # Dashboard functions
    "compute_display_status",
    "db_get_issue_detail",
    "db_get_issues_paginated",
    "db_get_active_repos",
    "db_get_lgtm_leaderboard",
    "db_get_org_stats",
    "db_get_top_pr_authors",
    "db_get_workspace_executions",
    "db_get_workspace_pull_requests",
    "db_get_workspace_stats",
    "db_list_issue_repositories",
    "db_list_pr_repositories",
    # Workspace functions
    "db_create_workspace",
    "db_create_workspace_membership",
    "db_ensure_workspace_membership",
    "db_get_workspace_by_id",
    "db_get_workspace_by_slug",
    "db_get_workspaces_by_user",
    "db_is_workspace_member",
    "db_revoke_workspace_membership_if_no_orgs",
]
